### ISSUE TITLE
Working config for Svelte Kit?

### ISSUE THREAD

**Issue by lietu** [xiphux/svimg#26]
Anyone got a working config for svimg + Svelte Kit? I'm trying to set it up, don't run into errors, but it just .. doesn't work. I see no images generated in static/g, it creates empty folders instead.

**Comment by david-plugge** [comment]
This works for me

```svelte
<!-- src/routes/index.svelte -->
<script lang="ts">
	import Image from 'svimg';
</script>

<Image src="/img/one.jpg" width="400" alt="one" immediate />

<Image src="/img/two.jpg" width="500" alt="two" quality="50" />
```

````js
// svelte.config.js
import adapter from '@sveltejs/adapter-auto';
import preprocess from 'svelte-preprocess';
import { imagePreprocessor } from 'svimg';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: [
		preprocess(),
		imagePreprocessor({
			inputDir: 'static',
			outputDir: 'static/g',
			webp: true,
			avif: true
		})
	],

	kit: {
		adapter: adapter()
	}
};

export default config;
```

**Comment by lietu** [comment]
For a moment I thought the `/` prefix on `src` might've been the difference that matters for me, but nah. It's the only real difference I could quickly spot.

I got `static/images/forest.jpg`

Tried these:
```svelte
<!-- Component.svelte (also tried src/routes/index.svelte) -->
<script lang="ts">
  import Image from 'svimg'
</script>

<Image src="/images/forest.jpg" width="320" alt="Forest" immediate />
```
```js
// svelte.config.js
import adapter from '@sveltejs/adapter-auto'
import preprocess from 'svelte-preprocess'
import { imagePreprocessor } from 'svimg'

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: [
    preprocess({
      scss: {
        prependData: '@use "src/styles/variables.scss" as *;',
      },
    }),
    imagePreprocessor({
      inputDir: 'static',
      outputDir: 'static/g',
      webp: true,
      avif: true,
    }),
  ],

  kit: {
    adapter: adapter(),
    trailingSlash: 'always',
  },
}

export default config
```
Just end up with empty `static/g/images` folder created.

**Comment by xiphux** [comment]
Would you happen to have a repro I could take a look at?

**Comment by lietu** [comment]
Unfortunately it's a closed project, might have to make a minimized copy for reproduction and well if it won't have the issue then try to figure out the difference 😄

**Comment by jgrieger** [comment]
I do have problems as well. Images get generated, but not displayed.

**Comment by xiphux** [comment]
If you're getting images generated, that sounds like a different problem. Check the urls that the srcset is trying to retrieve (eg with browser developer tools) vs what url the generated images are actually served from. You might need to define a `publicPath` to match them up.

**Comment by TheHelias** [comment]
So I noticed the images get generated and show up until I add the `width` prop to the component and then it stops showing. Here  is a repo you can take a look at

**Comment by xiphux** [comment]
Ok thanks, now I see what the problem with the missing files is. The preprocessor will fail to generate an image if you use an explicit width on the component and the width you specify is **larger** than the original file's width. In that case it's supposed to just use the original image's width as-is, since trying to blow the image up to the requested size would just take up extra disk space without any increase in quality - but due to a bug it's not requesting any image widths. I'll look at a fix.
