### ISSUE TITLE
Replace Sapper instructions with SvelteKit instructions

### ISSUE THREAD

**Issue by benmccann** [xiphux/svimg#27]
SvelteKit has a lot more users and Sapper has been deprecated and archived (see https://github.com/sveltejs/sapper), so I'd love to see SvelteKit instructions take the place of the Sapper instructions on the README :grin:

**Comment by xiphux** [comment]
I was waiting for SvelteKit to stabilize and leave beta, but if we've archived Sapper I guess that ship has sailed.
