### ISSUE TITLE
Could it somehow be used for background-images?

### ISSUE THREAD

**Issue by OClement** [xiphux/svimg#30]
My understanding is that it is only usable through the <Image> component, which generate the needed DOM;

So, as the title says; how could we go about using the pre-processor and maybe a Svelte directive in order to be able to use the optimized images as a background image on some div?

**Comment by xiphux** [comment]
Not in a very straightforward way yet... The best way to support this in the future as a CSS background image would be to use the `image-set` css directive, but [browser support is currently quite spotty](https://caniuse.com/?search=image-set).

I haven't tried it myself yet, but you may be able to make it a pseudo-background-image with some CSS. Something like putting it inside a div with relative position and explicit width/height, and inside that, styling either the Image (or an inner div containing the image) with absolute position. [Something sort of like this](https://stackoverflow.com/a/46836357).

**Comment by OClement** [comment]
Yeah I thought so, but was hoping there would have been something more straightforward I didn’t think of. 

I’m actually using the relative/absolute positioning work around in the meantime, but it’s sometimes a bit problematic. 

Thanks for the speedy reply’
