### ISSUE TITLE
ResizeObserver.observe: Argument 1 is not an object.

### ISSUE THREAD

**Issue by damilgra** [xiphux/svimg#34]
I'm seeing the following traceback for _certain_ images that get processed. If I stick a console.log on the container object I can't see any obvious differences between elements that don't produce the traceback and those that do, however.

```
Uncaught (in promise) TypeError: ResizeObserver.observe: Argument 1 is not an object.
    instance Image.svelte:73
    promise callback*instance/< Image.svelte:64
    run index.mjs:18
    mount_component index.mjs:1932
    flush index.mjs:1173
    init index.mjs:2027
    Root root.svelte:916
    createProxiedComponent svelte-hooks.js:341
    ProxyComponent proxy.js:242
    Proxy<Root> proxy.js:349
    initialize client.js:378
    _hydrate client.js:1563
    start start.js:31
    <anonymous> research:3426
Image.svelte:73:11
    instance Image.svelte:73
    (Async: promise callback)
    instance Image.svelte:64
    run index.mjs:18
    map self-hosted:221
    mount_component index.mjs:1932
    flush index.mjs:1173
    init index.mjs:2027
    Root root.svelte:916
    createProxiedComponent svelte-hooks.js:341
    ProxyComponent proxy.js:242
    Proxy<Root> proxy.js:349
    initialize client.js:378
    _hydrate client.js:1563
    AsyncFunctionNext self-hosted:807
    (Async: async)
    start start.js:31
    <anonymous> research:3426
```

**Comment by xiphux** [comment]
Is it consistently reproducible for the same certain images, or does it happen intermittently for a given image? What version of Svelte and browser is this?

I know there's been occasional issues around the timing of Svelte's bind:this and its availability in onMount, both within Svelte itself as well as timing differences between browsers. Wonder if something got reintroduced.

**Comment by SirNovi** [comment]
I assume I have the same issue. It tells me 
`Image.svelte:71 Uncaught (in promise) TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'. at Image.svelte:71:12`

but not on initial page load, only when returning page after navigating away.

svelte 3.54.0, Chrome 108.0.5359.124

**Comment by futantan** [comment]
same here. anything I can do to fix this?

**Comment by xiphux** [comment]
If anyone has a minimal reproduction, that would be helpful - I've been having difficulty recreating the specific conditions on my end.

**Comment by futantan** [comment]
I guess I find a way to reproduce:

```html
<MediaQuery query="(min-width: 940px)" let:matches>
  {#if matches}
    <Image src="/images/custom-desc.png" class="h-auto w-full" alt="custom pictures" />
  {:else}
    <Image
      src="/images/custom-collectable-mobile.png"
      class="h-auto w-full"
      alt="custom pictures"
    />
  {/if}
</MediaQuery>
```

and the code of `MediaQuery`

```html
<script lang="ts">
  import { onMount } from 'svelte';

  export let query: string;

  let mql: MediaQueryList;
  let mqlListener: (e: MediaQueryListEvent) => void;
  let wasMounted = false;
  let matches = false;

  onMount(() => {
    wasMounted = true;
    return () => {
      removeActiveListener();
    };
  });

  $: {
    if (wasMounted) {
      removeActiveListener();
      addNewListener(query);
    }
  }

  function addNewListener(query: string) {
    mql = window.matchMedia(query);
    mqlListener = (v: MediaQueryListEvent) => {
      matches = v.matches;
    };
    mql.addEventListener('change', mqlListener);

    matches = mql.matches;
  }

  function removeActiveListener() {
    if (mql && mqlListener) {
      mql.removeEventListener('change', mqlListener);
    }
  }
</script>

<slot {matches} />
```

the `matches` will be `false` and then `true`, and then the error shows

@xiphux

**Comment by xiphux** [comment]
Thanks, I think I see what's happening.

In earlier versions of Svelte, there was an issue where `onMount` would fire before `bind:this` element references were established (needed for `ResizeObserver`), so svimg would do a `tick` in `onMount` to let the DOM settle before initializing the `ResizeObserver`. However, in a scenario like this, where an `Image` may be rapidly conditionally shown and then hidden, the component may have already been unmounted and removed from the DOM by the time the `tick` fired, so our element reference was gone by that point. The error seems generally benign since the component's already been unmounted, but it's still noisy.

I think I can add some better handling for this scenario. It seems like the `bind:this` reference is more reliably available in `onMount` in more recent versions of Svelte without needing the `tick`, as well, which helps.
