### ISSUE TITLE
Unable to install with Svelte 4

### ISSUE THREAD

**Issue by manuganji** [xiphux/svimg#42]
Hi, after migrating to Svelte 4 following the guide at https://svelte.dev/docs/v4-migration-guide, I can't install this package. I tried to debug the problem but I don't have any clue yet except the obvious that it's something related to Svelte dropping commonjs support.

> Error [ERR_REQUIRE_ESM]: require() of ES Module ../node_modules/svelte/src/runtime/ssr.js from .../node_modules/svimg/dist/index.js not supported.
> Instead change the require of ssr.js in .../node_modules/svimg/dist/index.js to a dynamic import() which is available in all CommonJS modules.
>     at Object.<anonymous> (../node_modules/svimg/dist/index.js:15:14)
>     at async Promise.all (index 0)
>     at async load_config (file:///.../node_modules/@sveltejs/kit/src/core/

**Comment by laugepetersen** [comment]
How can we use your pr as part of our application meanwhile it get's merged?

**Comment by laugepetersen** [comment]
Exactly, so what to do in that case?

**Comment by falcyon** [comment]
Hi! Thank you for working on this! Seems to be a super helpful component! I'm trying to add it to my project but I get a similar error when I try to run a dev server or a build. (My project is built on default Sveltekit and my understanding is, it doesnt need an external rollup). 

> error when starting dev server:
Error [ERR_REQUIRE_ESM]: require() of ES Module ..\node_modules\svelte\src\runtime\ssr.js from ..\node_modules\svimg\dist\index.js not supported.
Instead change the require of ssr.js in ..\node_modules\svimg\dist\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (..\node_modules\svimg\dist\index.js:15:14)


The line in question seems to be-

> var svelte = require('svelte');

Any help would be appreciated.

**Comment by xiphux** [comment]
See https://github.com/xiphux/svimg/issues/47#issuecomment-1802132920 which should be released soon.

**Comment by falcyon** [comment]
Oh thank you! You're a godsend!
