### ISSUE TITLE
Bug: require() is trying to import an ES Module

### ISSUE THREAD

**Issue by dnlml** [xiphux/svimg#47]
### Description:
In Sveltekit, after installing svimg (`pnpm i svimg`) as dependency, running `pnpm dev` does not work.

```
error when starting dev server:
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/-/-/node_modules/.pnpm/svelte@4.2.0/node_modules/svelte/src/runtime/ssr.js from /Users/-/-/node_modules/.pnpm/svimg@3.2.0/node_modules/svimg/dist/index.js not supported.
Instead change the require of ssr.js in /Users/-/-/node_modules/.pnpm/svimg@3.2.0/node_modules/svimg/dist/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/-/-/node_modules/.pnpm/svimg@3.2.0/node_modules/svimg/dist/index.js:15:14)
 ELIFECYCLE  Command failed with exit code 1.
```

### Versions
- Node: 18.16.0
- pnpm: 8.6.1

**Comment by shalawfatah** [comment]
Same issue here. I use `npm` and `SvelteKit`

**Comment by dukejones** [comment]
Yep, pnpm explodes horribly.

**Comment by dukejones** [comment]
Anyone try pulling all the old `require(...)` calls out of the svimg library?

**Comment by dukejones** [comment]
Looks like the `master` branch runs fine, if you download and build it, then point package.json to the local dir.

IIRC, it's common to commit build artifacts to repos of npm repositories, so you can point your package.json to github directly.

**Comment by dukejones** [comment]
Dang, I forked the repo, common dist/, and pnpm is throwing the same error. Works fun when pointed to local directory.

**Comment by nelsonvassalo** [comment]
Also going through this.

**Comment by jeffrey0606** [comment]
having the same issue 🖐️

**Comment by feavel1** [comment]
Same

**Comment by feavel1** [comment]
Any one have encountered the same issue? Can you describe how to solve it???

**Comment by dukejones** [comment]
no solution yet..... i'd love to use svimg but no way i'm ditching pnpm

**Comment by hexahigh** [comment]
@dukejones How do you point it to a local directory? Do i need to build it first?

**Comment by dukejones** [comment]
Yeah, IIRC I checked out the repo locally, did a full build, then in package.json just "svimg": "../svimg"

**Comment by xiphux** [comment]
The problem is that Svelte 4 moved to be pure ES modules, whereas svimg still builds CommonJS modules by default. (svimg does provide ES modules as well, but in a sort of nonstandard way from before Node settled on its standard ESM support)

I'm working on converting svimg to pure ESM. It'll have to be a major version breaking change.

**Comment by dukejones** [comment]
Thanks for the analysis! CJS vs ESM, and different standards on the way are pretty confusing.

Need a hand with the ESM conversion?

**Comment by xiphux** [comment]
Thanks for the offer, but I think I've gotten the necessary changes completed. Current git is now ESM, hoping to do a release in the next day or so.
