### ISSUE TITLE
Doesn't work with sveltekit 1.27.7

### ISSUE THREAD

**Issue by ErikSandquist** [xiphux/svimg#51]
After updating to sveltekit 1.27.7 i get the error:
![image](https://github.com/xiphux/svimg/assets/67651948/f7eb5acf-6739-48f0-b559-99c4416ad585)

And in the console:
```[vite] Error when evaluating SSR module /src/lib/AudioDemo.svelte: failed to import "/node_modules/svimg/src/Image.svelte"```

This is with Svimg 4.0.0

**Comment by xiphux** [comment]
Can you double check that you're using an up to date svelte / vite-plugin-svelte? The customElement option is new in Svelte 4.

**Comment by ErikSandquist** [comment]
Was missing svelte 4, but after I updated I now get the error:
```
SyntaxError: The requested module '/node_modules/.vite/deps/svimg.js?v=331bcb0f' does not provide an export named 'default' (at Cart.svelte:4:9)
handleError @ app.js:42
```

And the code found at Cart.svelte is just:
```
import Image from 'svimg';
```

**Comment by xiphux** [comment]
Please refer to [the README](https://github.com/xiphux/svimg?tab=readme-ov-file#svelte-component) and the [CHANGELOG for 4.0.0](https://github.com/xiphux/svimg/blob/master/CHANGELOG.md#400). The entry point for the component changed in svimg 4.0.0.

**Comment by ErikSandquist** [comment]
Thank you for the help. That slipped by when updating.
